- name: write sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
  - reload sshd
- name: write authorized_keys
  template: src=authorized_keys.j2 dest=/root/.ssh/authorized_keys mode=600
  
